server:
    port: 8081

spring:
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: Iv1.37f5fac410568d4e
                        client-secret: d846b4b424798bdec279d60dcebf7d72fab547cc
                    
                    