server:
    port: 8081

spring:
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: <github-app-client-id> 
                        client-secret:  <github-app-client-secret>
                    google:
                        client-id:  <google-app-client-id>
                        client-secret:  <google-app-client-secret>
                    